params:
  profileMode:
    enabled: true
    title: "Hello" # optional default will be site title
    subtitle: "This is subtitle"
    imageUrl: "" # optional
    imageTitle: "" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: Archive
        url: "/archive"
      - name: Github
        url: "https://github.com/"

  socialIcons: # optional
    - name: "<platform>"
      url: "<link>"
    - name: "<platform 2>"
      url: "<link2>"

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

